### ISSUE TITLE
Cant Compile it (lto compiler error)

### ISSUE THREAD

**Issue by Kurainu** [Morilli/ManifestDownloader#4]
When i try to compile this Project i get an lto1 internal compiler error?

How can i fix this error?
![Screenshot from 2020-12-19 21-15-22](https://user-images.githubusercontent.com/15718492/102698815-844e5b80-4240-11eb-98ab-7ff0a45ead42.png)

**Comment by Morilli** [comment]
Yeah that one is caused due to me using and compiling with gcc 10 while you are using gcc 9. I compiled all *.a files with `-flto` which makes them larger, but improves the final binary size.

Apparently though, this makes the resulting files compiler-dependant, and they won't work with a different version anymore (at least not the version 10 ones with gcc 9).

I could either compile the .a files without the `flto` flag, or include the complete sources to have everyone compile them themselves; or maybe there is a way to make the files compiler-independant that I don't know about.

For the time being you can either use a gcc 10 version or compile the provided .a files yourself from their original sources, both of which can be annoying. I'll try and figure out whether there is something better I can do to make this work for everyone.

**Comment by Kurainu** [comment]
So I managed to compile the ManifestDownloader by compiling my own .a files for zstd and bearssl.  And i also can compile the ManifestDownloader now without a problem when i switch between gcc 10, 9 and 8 (with `sudo update-alternatives --config gcc`)

**Comment by Morilli** [comment]
I'm glad this worked for you now, but obviously this wasn't the best solution.

I've pushed some changes, including source code for all third-party libraries that I use, and added code in the makefile to build them automatically instead of distributing the built (and system-dependent) archive files.

I'd appreciate if you could test this on your end; it'd be nice to know whether it actually works without modifications on gcc 9 or lower now (it should!).

**Comment by Kurainu** [comment]
@Morilli i tested your change on my Ubuntu box but it doesnt worked because it either dont found the bearssl directory (because linux is case sensitive you know) or it doesnt recognized  parameters.

And this Error ocurrs:
![Unbenannt](https://user-images.githubusercontent.com/15718492/102983179-f73f2700-450b-11eb-845f-eb054add7236.png)

I Got it to compile Successfully on 10 and 9 and 8 (Version 7 which i have also installed errors out) after i modified the following points
- if you rename the folder BearSSL -> bearssl it can find that folder
- changed in the Makefile the line `CONF := unix` -> `CONF := Unix`

I you could it implement it would be great 👍

**Comment by Morilli** [comment]
Okay, thanks for that information! I didn't even notice any issues with that because I just tested on my NTFS filesystem. I didn't wanna rename the `BearSSL` folder so I've just fixed all references to it in my code; compilation should now work perfectly ™️ on both linux and windows filesystems.
